# Generated by Django 3.0.3 on 2020-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200407_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=13)),
                ('birthplace', models.CharField(max_length=64)),
                ('birthdate', models.DateField()),
                ('joindate', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=64)),
                ('salary', models.FloatField(max_length=13)),
            ],
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '房间信息', 'verbose_name_plural': '房间信息'},
        ),
        migrations.AlterField(
            model_name='room',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='房间名称'),
        ),
    ]
