# Generated by Django 2.2.8 on 2020-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200409_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.AlterField(
            model_name='book',
            name='time_id',
            field=models.IntegerField(choices=[(1, '0:00-1:00'), (2, '1:00-2:00'), (3, '2:00-3:00'), (4, '3:00-4:00'), (5, '4:00-5:00'), (6, '5:00-6:00'), (7, '6:00-7:00'), (8, '7:00-8:00'), (9, '8:00-9:00'), (10, '9:00-10:00'), (11, '10:00-11:00'), (12, '11:00-12:00'), (13, '12:00-13:00'), (14, '13:00-14:00'), (15, '14:00-15:00'), (16, '15:00-16:00'), (17, '16:00-17:00'), (18, '17:00-18:00'), (19, '18:00-19:00'), (20, '19:00-20:00'), (21, '20:00-21:00'), (22, '21:00-22:00'), (23, '22:00-23:00'), (24, '23:00-0:00'), (25, '0:00-12:00'), (26, '0:00-24:00')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthplace',
            field=models.CharField(max_length=64, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joindate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=64, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=64, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(max_length=13, verbose_name='薪资'),
        ),
    ]
